pragma Singleton
import QtQuick
import QtCore

QtObject {
    id: root
    property string currentTheme: _settings.theme
    onCurrentThemeChanged: _settings.theme = currentTheme
    property Settings _settings: Settings {
        category: "Appearance"
        property string theme: "normal"
    }
    property string iconPath: currentTheme === "dark" ? "../Resources/icons-light/" : "../Resources/"
    property QtObject themeNormal: QtObject {
        property color baseTextColor: "#1a1a1a"
        property color secondaryTextColor: "#222222"
        property color tertiaryTextColor: "#333333"
        property color disabledTextColor: "#555555"
        property color colorWhite: "white"
        property color baseInteractionHover: "#33000000"
        property color baseInteractionPressed: "#66000000"
        property color dialogBackground: "#8E9191"
        property color dialogHeaderBackground: "#7A7D7D"
        property color overlayColor: "#73000000"
        property color separatorColor: "#00000033"
        property color canvasBorderColor: "#444444"
        property real canvasBorderWidth: 4.0
        property real canvasBorderLen: 8.0
        property real dialogRadius: 4.0
        property int fontTitleSize: 20
        property int fontBodySize: 16
        property int fontWeight: Font.Medium
        property color titleColor: baseTextColor
        property color messageColor: secondaryTextColor
        property real customButtonHeight: 40
        property real buttonRadius: 8.0
        property color customButtonText: baseTextColor
        property color customButtonNormal: "transparent"
        property color customButtonHover: baseInteractionHover
        property color customButtonPressed: baseInteractionPressed
        property real menuWidth: 200
        property real menuRadius: 6.0
        property color menuBackground: dialogBackground
        property color menuBorder: dialogHeaderBackground
        property int menuTextSize: 14
        property color menuText: baseTextColor
        property real menuItemHeight: 55
        property real menuItemRadius: 8.0
        property real menuItemMargin: 4
        property color menuItemHover: baseInteractionHover
        property color menuItemPressed: baseInteractionPressed
        property real menuSeparatorHeight: 2
        property color menuSeparatorColor: dialogHeaderBackground
        property color btnCancelText: secondaryTextColor
        property color btnCancelNormal: "#848787"
        property color btnCancelHover: "#9EA1A1"
        property color btnCancelPressed: dialogHeaderBackground
        property color btnCancelBorder: "#00000022"
        property color btnConfirmText: baseTextColor
        property color btnConfirmNormal: "#AB4141"
        property color btnConfirmHover: "#C04040"
        property color btnConfirmPressed: "#8B2E2E"
        property int sliderTitleFontSize: 18
        property int sliderTitleFontWeight: Font.Medium
        property color sliderTitleColor: baseTextColor
        property real sliderBgImplicitWidth: 200
        property real sliderBgImplicitHeight: 8
        property real sliderBgRadius: 3
        property color sliderBgColor: "#555555"
        property real sliderHandleImplicitWidth: 22
        property real sliderHandleImplicitHeight: 22
        property real sliderHandleRadius: 9
        property color sliderHandleColor: colorWhite
        property color sliderHandleBorderColor: tertiaryTextColor
        property real sliderHandleBorderWidth: 1
        property real sliderResetBtnWidth: 115
        property real sliderResetBtnHeight: 16
        property int sliderResetBtnFontSize: 10
        property color sliderResetBtnTextColor: baseTextColor
        property real sliderResetBtnBgHeight: 3
        property color sliderResetBtnBgColor: "#D65151"
        property real sliderResetBtnBgRadius: 5
        property int sliderValueFontSize: 20
        property int sliderValueFontWeight: Font.Medium
        property color sliderValueColor: tertiaryTextColor
        property int iconButtonIconSize: 32
        property int iconButtonColorFillPadding: 8
        property real iconButtonDisabledOpacity: 0.2
        property real iconButtonNormalOpacity: 0.8
        property real iconButtonPressedScale: 0.9
        property int iconButtonAnimationDuration: 50
        property int iconButtonBgPadding: 10
        property color iconButtonSelectedColor: baseInteractionPressed
        property color iconButtonPressedColor: baseInteractionPressed
        property color iconButtonHoveredColor: baseInteractionHover
        property real iconButtonRadius: 8.0
        property int iconButtonTooltipDelay: 500
        property int filterButtonHeight: 70
        property int filterButtonSpacing: 3
        property color filterButtonHoverColor: baseInteractionHover
        property int filterButtonBorderHeight: 1
        property color filterButtonBorderColor: baseTextColor
        property int filterMenuWidth: 320
        property real filterMenuRadius: 4
        property color filterMenuBorderColor: baseTextColor
        property int filterMenuItemHeight: 70
        property int inputRowSpacing: 10
        property int inputLabelFontSize: 16
        property bool inputLabelFontBold: true
        property color inputLabelColor: secondaryTextColor
        property int inputLabelWidth: 150
        property int inputFieldRightMargin: 50
        property int inputFieldHeight: 35
        property real inputFieldRadius: 4
        property color inputFieldBgReadOnly: dialogBackground
        property color inputFieldBgNormal: "#9B9D9E"
        property color inputFieldFocusBorderColor: "#3498db"
        property int inputFieldBorderWidth: 1
        property color inputFieldTextReadOnly: tertiaryTextColor
        property color inputFieldTextNormal: secondaryTextColor
        property int inputFieldFontSize: 15
        property int inputFieldPaddingLeft: 10
        property int inputFieldPaddingRightIcon: 45
        property int inputFieldPaddingRight: 10
        property int inputIconSize: 24
        property int inputIconRightMargin: 12
        property real inputIconFocusOpacity: 0.7
        property real inputIconNormalOpacity: 0.35
        property int startScreenIconColumnWidth: 100
        property int startScreenTopMargin: 60
        property int startScreenLayoutSpacing: 10
        property int startScreenOpenAreaHeight: 120
        property int startScreenOpenAreaBgMargin: -10
        property real startScreenOpenAreaRadius: 10
        property color startScreenOpenAreaHover: "#6F7373"
        property int startScreenOpenIconSize: 80
        property int startScreenOpenTextSize: 45
        property int startScreenOpenTextWeight: Font.DemiBold
        property int startScreenRecentIconSize: 60
        property real startScreenRecentIconOpacity: 0.5
        property int startScreenRecentTextSize: 32
        property int startScreenRecentTextWeight: Font.DemiBold
        property int startScreenHistoryItemHeight: 70
        property real startScreenHistoryItemRadius: 5
        property int startScreenHistoryItemSpacing: 15
        property int startScreenThumbSize: 50
        property real startScreenThumbRadius: 6
        property color startScreenThumbBgColor: "#cccccc"
        property int startScreenDeleteButtonSize: 35
        property real startScreenDeleteButtonRadius: 5
        property color startScreenDeleteButtonHoverColor: disabledTextColor
        property int scrollBarWidth: 8
        property real scrollBarRadius: 4
        property color metadataRightPanelBg: "#C0C3C4"
        property int metadataTopBarHeight: 50
        property int metadataLeftPanelWidth: 150
        property int metadataPanelMargin: 10
        property int metadataPanelSpacing: 12
        property int metadataActionBtnSize: 50
        property int metadataActionIconSize: 35
        property real metadataDisabledIconOpacity: 0.25
        property int metadataContentMargin: 20
        property int metadataScrollMargin: 15
        property int metadataContentSpacing: 8
        property int metadataSeparatorHeight: 1
        property color metadataSeparatorColor: "#777777"
        property int metadataRowWidthLarge: 450
        property int metadataRowWidthSmall: 300
        property real metadataReadOnlyOpacity: 0.8
        property int metadataDescriptionHeight: 80
        property int metadataDescriptionLabelTopMargin: 6
        property int metadataDescriptionPaddingTop: 6
        property int metadataDescriptionPaddingBottom: 6
        property int metadataDescriptionPaddingLeft: 8
        property int metadataDescriptionPaddingRight: 45
        property int metadataSaveBtnWidth: 150
        property int metadataSaveBtnHeight: 50
        property int metadataSaveBtnFontSize: 18
        property color metadataSaveBtnNormal: "#3498db"
        property color metadataSaveBtnHover: "#5dade2"
        property color metadataSaveBtnPressed: "#2980b9"
        property real metadataSaveBtnRadius: 6
        property int metadataBottomBarHeight1: 60
        property int metadataBottomBarHeight2: 50
        property color metadataBottomBarColor2: "#A0A3A3"
        property color cancelActionBtnNormal: "#AB4141"
        property color cancelActionBtnHover: "#C45454"
        property color cancelActionBtnPressed: "#A34141"
        property int manipulationTopBarHeight: 50
        property int manipulationSidePanelWidth: 150
        property int manipulationPanelMargin: 10
        property int manipulationPanelSpacing: 12
        property int manipulationRotationSliderHeight: 475
        property int manipulationRotationSliderBgWidth: 40
        property int manipulationRotationSliderBgHeight: 270
        property int manipulationRotationSliderTrackWidth: 4
        property color manipulationRotationSliderTrackColor: canvasBorderColor
        property int manipulationRotationSliderTickWidthLarge: 25
        property int manipulationRotationSliderTickWidthSmall: 15
        property int manipulationRotationSliderTickHeightLarge: 5
        property int manipulationRotationSliderTickHeightSmall: 2
        property color manipulationRotationSliderTickColorActive: baseTextColor
        property color manipulationRotationSliderTickColorInactive: baseTextColor
        property int manipulationRotationSliderHandleSize: 24
        property real manipulationRotationSliderHandleRadius: 12
        property color manipulationRotationSliderHandleColor: colorWhite
        property color manipulationRotationSliderHandlePressedColor: "#f0f0f0"
        property color manipulationRotationSliderHandleBorderColor: tertiaryTextColor
        property int manipulationGridBtnSize: 50
        property int manipulationGridSpacing: 10
        property color manipulationConfirmBtnNormal: "#2980b9"
        property color manipulationConfirmBtnHover: "#3498db"
        property color manipulationConfirmBtnPressed: "#217dbb"
        property real manipulationConfirmBtnRadius: 4
        property color manipulationCropMaskColor: "#80000000"
        property int manipulationCropHandleBaseSize: 26
        property color manipulationCropHandleColor: colorWhite
        property color manipulationCropHandleBorderColor: baseTextColor
        property color manipulationPanBtnActiveColor: baseInteractionPressed
        property color manipulationPanBtnHoverColor: baseInteractionHover
        property int manipulationZoomSliderWidth: 250
        property int manipulationZoomSliderBgWidth: 120
        property int manipulationZoomSliderBgHeight: 6
        property real manipulationZoomSliderBgRadius: 2
        property color manipulationZoomSliderBgColor: "#555555"
        property int manipulationZoomSliderHandleSize: 16
        property real manipulationZoomSliderHandleRadius: 8
        property color manipulationZoomSliderHandleColor: colorWhite
        property color manipulationZoomSliderHandleBorderColor: tertiaryTextColor
        property int manipulationBottomBarHeight1: 60
        property int manipulationBottomBarHeight2: 50
        property color manipulationBottomBarColor2: "#A0A3A3"
        property int manipulationZoomBtnSpacing: 5
        property int filterStrengthSpacing: 20
        property int filterStrengthSeparatorHeight: 1
        property real filterStrengthSeparatorOpacity: 0.2
        property int filterStrengthTextSize: 18
        property int filterStrengthTextHeight: 45
        property int filterStrengthSliderHeight: 30
        property int filterStrengthSliderBgWidth: 130
        property int editorCornerListSpacing: 8
        property int editorCornerScrollBarWidth: 6
        property int editorCornerScrollBarRadius: 3
        property int editorToolBtnMinWidth: 130
        property int editorToolBtnHeight: 50
        property int editorToolBtnSpacing: 10
        property int editorToolBtnPadding: 15
        property int editorToolBtnIconSize: 28
        property int editorBottomBarSpacing: 15
        property int editorBottomBarMargin: 20
        property real editorInfoIconOpacity: 0.7
        property color editorOverlayBg: "#000000"
        property real editorPrintingOverlayOpacity: 0.6
        property real editorSaveOverlayOpacity: 0.7
        property int editorOverlayTextSizeLarge: 24
        property int editorOverlayTextSizeMedium: 22
        property color editorOverlayTextColor: colorWhite
        property int editorOverlayTextMargin: 40
        property int editorProgressBarHeight: 6
        property color editorProgressBarBgColor: canvasBorderColor
        property real editorProgressBarRadius: 3
        property color editorProgressBarFillColor: "#AC4141"
        property real editorProgressBarFillRadius: 2
        property real editorPrintingAnimOpacityMin: 0.3
        property real editorPrintingBtnDisabledOpacity: 0.6
        property int drawingToolGridSpacing: 10
        property int drawingToolBtnSize: 60
        property int drawingToolIconSize: 50
        property int drawingDividerWidth: 130
        property int drawingSettingsSpacing: 10
        property int drawingSettingsWidth: 130
        property int drawingSettingsGroupSpacing: 15
        property int drawingSectionTitleSize: 22
        property int drawingSettingLabelSize: 15
        property int drawingColorSliderHeight: 20
        property color drawingRgbRedBg: "#ffcccc"
        property color drawingRgbGreenBg: "#ccffcc"
        property color drawingRgbBlueBg: "#ccccff"
        property color drawingTextSelectionColor: "#aaaaaa"
    }

    property QtObject themeLight: QtObject {
        property color baseTextColor: "#111111"
        property color secondaryTextColor: "#222222"
        property color tertiaryTextColor: "#444444"
        property color disabledTextColor: "#888888"
        property color colorWhite: "#FFFFFF"
        property color baseInteractionHover: "#1A000000"
        property color baseInteractionPressed: "#33000000"
        property color dialogBackground: "#F0F2F5"
        property color dialogHeaderBackground: "#E1E4E8"
        property color overlayColor: "#4D000000"
        property color separatorColor: "#0000001A"
        property color canvasBorderColor: "#666666"
        property real canvasBorderWidth: 4.0
        property real canvasBorderLen: 8.0
        property real dialogRadius: 4.0
        property int fontTitleSize: 20
        property int fontBodySize: 16
        property int fontWeight: Font.Medium
        property color titleColor: baseTextColor
        property color messageColor: secondaryTextColor
        property real customButtonHeight: 40
        property real buttonRadius: 8.0
        property color customButtonText: baseTextColor
        property color customButtonNormal: "transparent"
        property color customButtonHover: baseInteractionHover
        property color customButtonPressed: baseInteractionPressed
        property real menuWidth: 200
        property real menuRadius: 6.0
        property color menuBackground: dialogBackground
        property color menuBorder: dialogHeaderBackground
        property int menuTextSize: 14
        property color menuText: baseTextColor
        property real menuItemHeight: 55
        property real menuItemRadius: 8.0
        property real menuItemMargin: 4
        property color menuItemHover: baseInteractionHover
        property color menuItemPressed: baseInteractionPressed
        property real menuSeparatorHeight: 2
        property color menuSeparatorColor: dialogHeaderBackground
        property color btnCancelText: secondaryTextColor
        property color btnCancelNormal: "#D1D5DB"
        property color btnCancelHover: "#E5E7EB"
        property color btnCancelPressed: "#B0B5BC"
        property color btnCancelBorder: "#0000001A"
        property color btnConfirmText: "#FFFFFF"
        property color btnConfirmNormal: "#D32F2F"
        property color btnConfirmHover: "#E53935"
        property color btnConfirmPressed: "#B71C1C"
        property int sliderTitleFontSize: 18
        property int sliderTitleFontWeight: Font.Medium
        property color sliderTitleColor: baseTextColor
        property real sliderBgImplicitWidth: 200
        property real sliderBgImplicitHeight: 8
        property real sliderBgRadius: 3
        property color sliderBgColor: "#ADBAC7"
        property real sliderHandleImplicitWidth: 22
        property real sliderHandleImplicitHeight: 22
        property real sliderHandleRadius: 9
        property color sliderHandleColor: colorWhite
        property color sliderHandleBorderColor: "#64748B"
        property real sliderHandleBorderWidth: 1
        property real sliderResetBtnWidth: 115
        property real sliderResetBtnHeight: 16
        property int sliderResetBtnFontSize: 10
        property color sliderResetBtnTextColor: baseTextColor
        property real sliderResetBtnBgHeight: 3
        property color sliderResetBtnBgColor: "#EF4444"
        property real sliderResetBtnBgRadius: 5
        property int sliderValueFontSize: 20
        property int sliderValueFontWeight: Font.Medium
        property color sliderValueColor: tertiaryTextColor
        property int iconButtonIconSize: 32
        property int iconButtonColorFillPadding: 8
        property real iconButtonDisabledOpacity: 0.2
        property real iconButtonNormalOpacity: 0.8
        property real iconButtonPressedScale: 0.9
        property int iconButtonAnimationDuration: 50
        property int iconButtonBgPadding: 10
        property color iconButtonSelectedColor: baseInteractionPressed
        property color iconButtonPressedColor: baseInteractionPressed
        property color iconButtonHoveredColor: baseInteractionHover
        property real iconButtonRadius: 8.0
        property int iconButtonTooltipDelay: 500
        property int filterButtonHeight: 70
        property int filterButtonSpacing: 3
        property color filterButtonHoverColor: baseInteractionHover
        property int filterButtonBorderHeight: 1
        property color filterButtonBorderColor: baseTextColor
        property int filterMenuWidth: 320
        property real filterMenuRadius: 4
        property color filterMenuBorderColor: baseTextColor
        property int filterMenuItemHeight: 70
        property int inputRowSpacing: 10
        property int inputLabelFontSize: 16
        property bool inputLabelFontBold: true
        property color inputLabelColor: secondaryTextColor
        property int inputLabelWidth: 150
        property int inputFieldRightMargin: 50
        property int inputFieldHeight: 35
        property real inputFieldRadius: 4
        property color inputFieldBgReadOnly: dialogBackground
        property color inputFieldBgNormal: "#FFFFFF"
        property color inputFieldFocusBorderColor: "#3B82F6"
        property int inputFieldBorderWidth: 1
        property color inputFieldTextReadOnly: tertiaryTextColor
        property color inputFieldTextNormal: secondaryTextColor
        property int inputFieldFontSize: 15
        property int inputFieldPaddingLeft: 10
        property int inputFieldPaddingRightIcon: 45
        property int inputFieldPaddingRight: 10
        property int inputIconSize: 24
        property int inputIconRightMargin: 12
        property real inputIconFocusOpacity: 0.8
        property real inputIconNormalOpacity: 0.4
        property int startScreenIconColumnWidth: 100
        property int startScreenTopMargin: 60
        property int startScreenLayoutSpacing: 10
        property int startScreenOpenAreaHeight: 120
        property int startScreenOpenAreaBgMargin: -10
        property real startScreenOpenAreaRadius: 10
        property color startScreenOpenAreaHover: "#D7D9DE"
        property int startScreenOpenIconSize: 80
        property int startScreenOpenTextSize: 45
        property int startScreenOpenTextWeight: Font.DemiBold
        property int startScreenRecentIconSize: 60
        property real startScreenRecentIconOpacity: 0.5
        property int startScreenRecentTextSize: 32
        property int startScreenRecentTextWeight: Font.DemiBold
        property int startScreenHistoryItemHeight: 70
        property real startScreenHistoryItemRadius: 5
        property int startScreenHistoryItemSpacing: 15
        property int startScreenThumbSize: 50
        property real startScreenThumbRadius: 6
        property color startScreenThumbBgColor: "#D7D9DE"
        property int startScreenDeleteButtonSize: 35
        property real startScreenDeleteButtonRadius: 5
        property color startScreenDeleteButtonHoverColor: disabledTextColor
        property int scrollBarWidth: 8
        property real scrollBarRadius: 4
        property color metadataRightPanelBg: "#E8EAED"
        property int metadataTopBarHeight: 50
        property int metadataLeftPanelWidth: 150
        property int metadataPanelMargin: 10
        property int metadataPanelSpacing: 12
        property int metadataActionBtnSize: 50
        property int metadataActionIconSize: 35
        property real metadataDisabledIconOpacity: 0.25
        property int metadataContentMargin: 20
        property int metadataScrollMargin: 15
        property int metadataContentSpacing: 8
        property int metadataSeparatorHeight: 1
        property color metadataSeparatorColor: "#D1D5DB"
        property int metadataRowWidthLarge: 450
        property int metadataRowWidthSmall: 300
        property real metadataReadOnlyOpacity: 0.8
        property int metadataDescriptionHeight: 80
        property int metadataDescriptionLabelTopMargin: 6
        property int metadataDescriptionPaddingTop: 6
        property int metadataDescriptionPaddingBottom: 6
        property int metadataDescriptionPaddingLeft: 8
        property int metadataDescriptionPaddingRight: 45
        property int metadataSaveBtnWidth: 150
        property int metadataSaveBtnHeight: 50
        property int metadataSaveBtnFontSize: 18
        property color metadataSaveBtnNormal: "#3B82F6"
        property color metadataSaveBtnHover: "#60A5FA"
        property color metadataSaveBtnPressed: "#2563EB"
        property real metadataSaveBtnRadius: 6
        property int metadataBottomBarHeight1: 60
        property int metadataBottomBarHeight2: 50
        property color metadataBottomBarColor2: "#D1D5DB"
        property color cancelActionBtnNormal: "#D32F2F"
        property color cancelActionBtnHover: "#EF4444"
        property color cancelActionBtnPressed: "#B71C1C"
        property int manipulationTopBarHeight: 50
        property int manipulationSidePanelWidth: 150
        property int manipulationPanelMargin: 10
        property int manipulationPanelSpacing: 12
        property int manipulationRotationSliderHeight: 475
        property int manipulationRotationSliderBgWidth: 40
        property int manipulationRotationSliderBgHeight: 270
        property int manipulationRotationSliderTrackWidth: 4
        property color manipulationRotationSliderTrackColor: canvasBorderColor
        property int manipulationRotationSliderTickWidthLarge: 25
        property int manipulationRotationSliderTickWidthSmall: 15
        property int manipulationRotationSliderTickHeightLarge: 5
        property int manipulationRotationSliderTickHeightSmall: 2
        property color manipulationRotationSliderTickColorActive: baseTextColor
        property color manipulationRotationSliderTickColorInactive: baseTextColor
        property int manipulationRotationSliderHandleSize: 24
        property real manipulationRotationSliderHandleRadius: 12
        property color manipulationRotationSliderHandleColor: colorWhite
        property color manipulationRotationSliderHandlePressedColor: "#F3F4F6"
        property color manipulationRotationSliderHandleBorderColor: tertiaryTextColor
        property int manipulationGridBtnSize: 50
        property int manipulationGridSpacing: 10
        property color manipulationConfirmBtnNormal: "#2563EB"
        property color manipulationConfirmBtnHover: "#3B82F6"
        property color manipulationConfirmBtnPressed: "#1D4ED8"
        property real manipulationConfirmBtnRadius: 4
        property color manipulationCropMaskColor: "#4D000000"
        property int manipulationCropHandleBaseSize: 26
        property color manipulationCropHandleColor: colorWhite
        property color manipulationCropHandleBorderColor: baseTextColor
        property color manipulationPanBtnActiveColor: baseInteractionPressed
        property color manipulationPanBtnHoverColor: baseInteractionHover
        property int manipulationZoomSliderWidth: 250
        property int manipulationZoomSliderBgWidth: 120
        property int manipulationZoomSliderBgHeight: 6
        property real manipulationZoomSliderBgRadius: 2
        property color manipulationZoomSliderBgColor: "#ADBAC7"
        property int manipulationZoomSliderHandleSize: 16
        property real manipulationZoomSliderHandleRadius: 8
        property color manipulationZoomSliderHandleColor: colorWhite
        property color manipulationZoomSliderHandleBorderColor: tertiaryTextColor
        property int manipulationBottomBarHeight1: 60
        property int manipulationBottomBarHeight2: 50
        property color manipulationBottomBarColor2: "#DCE0E3"
        property int manipulationZoomBtnSpacing: 5
        property int filterStrengthSpacing: 20
        property int filterStrengthSeparatorHeight: 1
        property real filterStrengthSeparatorOpacity: 0.2
        property int filterStrengthTextSize: 18
        property int filterStrengthTextHeight: 45
        property int filterStrengthSliderHeight: 30
        property int filterStrengthSliderBgWidth: 130
        property int editorCornerListSpacing: 8
        property int editorCornerScrollBarWidth: 6
        property int editorCornerScrollBarRadius: 3
        property int editorToolBtnMinWidth: 130
        property int editorToolBtnHeight: 50
        property int editorToolBtnSpacing: 10
        property int editorToolBtnPadding: 15
        property int editorToolBtnIconSize: 28
        property int editorBottomBarSpacing: 15
        property int editorBottomBarMargin: 20
        property real editorInfoIconOpacity: 0.6
        property color editorOverlayBg: "#000000"
        property real editorPrintingOverlayOpacity: 0.6
        property real editorSaveOverlayOpacity: 0.7
        property int editorOverlayTextSizeLarge: 24
        property int editorOverlayTextSizeMedium: 22
        property color editorOverlayTextColor: colorWhite
        property int editorOverlayTextMargin: 40
        property int editorProgressBarHeight: 6
        property color editorProgressBarBgColor: "#9CA3AF"
        property real editorProgressBarRadius: 3
        property color editorProgressBarFillColor: "#DC2626"
        property real editorProgressBarFillRadius: 2
        property real editorPrintingAnimOpacityMin: 0.3
        property real editorPrintingBtnDisabledOpacity: 0.6
        property int drawingToolGridSpacing: 10
        property int drawingToolBtnSize: 60
        property int drawingToolIconSize: 50
        property int drawingDividerWidth: 130
        property int drawingSettingsSpacing: 10
        property int drawingSettingsWidth: 130
        property int drawingSettingsGroupSpacing: 15
        property int drawingSectionTitleSize: 22
        property int drawingSettingLabelSize: 15
        property int drawingColorSliderHeight: 20
        property color drawingRgbRedBg: "#FECACA"
        property color drawingRgbGreenBg: "#BBF7D0"
        property color drawingRgbBlueBg: "#BFDBFE"
        property color drawingTextSelectionColor: "#93C5FD"
    }

    property QtObject themeDark: QtObject {
        property color baseTextColor: "#E5E7EB"
        property color secondaryTextColor: "#E5E7EB"
        property color tertiaryTextColor: "#9CA3AF"
        property color disabledTextColor: "#6B7280"
        property color colorWhite: "#F9FAFB"
        property color baseInteractionHover: "#5A9494"
        property color baseInteractionPressed: "#69B8B8"
        property color dialogBackground: "#1F2937"
        property color dialogHeaderBackground: "#111827"
        property color overlayColor: "#35354A"
        property color separatorColor: "#FFFFFF"
        property color canvasBorderColor: "#6B7280"
        property real canvasBorderWidth: 4.0
        property real canvasBorderLen: 8.0
        property real dialogRadius: 4.0
        property int fontTitleSize: 20
        property int fontBodySize: 16
        property int fontWeight: Font.Medium
        property color titleColor: baseTextColor
        property color messageColor: secondaryTextColor
        property real customButtonHeight: 40
        property real buttonRadius: 8.0
        property color customButtonText: baseTextColor
        property color customButtonNormal: "transparent"
        property color customButtonHover: baseInteractionHover
        property color customButtonPressed: baseInteractionPressed
        property real menuWidth: 200
        property real menuRadius: 6.0
        property color menuBackground: dialogBackground
        property color menuBorder: dialogHeaderBackground
        property int menuTextSize: 14
        property color menuText: baseTextColor
        property real menuItemHeight: 55
        property real menuItemRadius: 8.0
        property real menuItemMargin: 4
        property color menuItemHover: baseInteractionHover
        property color menuItemPressed: baseInteractionPressed
        property real menuSeparatorHeight: 2
        property color menuSeparatorColor: dialogHeaderBackground
        property color btnCancelText: secondaryTextColor
        property color btnCancelNormal: "#374151"
        property color btnCancelHover: "#4B5563"
        property color btnCancelPressed: "#1F2937"
        property color btnCancelBorder: "#FFFFFF"
        property color btnConfirmText: "#FFFFFF"
        property color btnConfirmNormal: "#DC2626"
        property color btnConfirmHover: "#EF4444"
        property color btnConfirmPressed: "#B91C1C"
        property int sliderTitleFontSize: 18
        property int sliderTitleFontWeight: Font.Medium
        property color sliderTitleColor: baseTextColor
        property real sliderBgImplicitWidth: 200
        property real sliderBgImplicitHeight: 8
        property real sliderBgRadius: 3
        property color sliderBgColor: "#4B5563"
        property real sliderHandleImplicitWidth: 22
        property real sliderHandleImplicitHeight: 22
        property real sliderHandleRadius: 9
        property color sliderHandleColor: colorWhite
        property color sliderHandleBorderColor: "#9CA3AF"
        property real sliderHandleBorderWidth: 1
        property real sliderResetBtnWidth: 115
        property real sliderResetBtnHeight: 16
        property int sliderResetBtnFontSize: 10
        property color sliderResetBtnTextColor: baseTextColor
        property real sliderResetBtnBgHeight: 3
        property color sliderResetBtnBgColor: "#EF4444"
        property real sliderResetBtnBgRadius: 5
        property int sliderValueFontSize: 20
        property int sliderValueFontWeight: Font.Medium
        property color sliderValueColor: tertiaryTextColor
        property int iconButtonIconSize: 32
        property int iconButtonColorFillPadding: 8
        property real iconButtonDisabledOpacity: 0.2
        property real iconButtonNormalOpacity: 0.8
        property real iconButtonPressedScale: 0.9
        property int iconButtonAnimationDuration: 50
        property int iconButtonBgPadding: 10
        property color iconButtonSelectedColor: baseInteractionPressed
        property color iconButtonPressedColor: baseInteractionPressed
        property color iconButtonHoveredColor: baseInteractionHover
        property real iconButtonRadius: 8.0
        property int iconButtonTooltipDelay: 500
        property int filterButtonHeight: 70
        property int filterButtonSpacing: 3
        property color filterButtonHoverColor: baseInteractionHover
        property int filterButtonBorderHeight: 1
        property color filterButtonBorderColor: baseTextColor
        property int filterMenuWidth: 320
        property real filterMenuRadius: 4
        property color filterMenuBorderColor: baseTextColor
        property int filterMenuItemHeight: 70
        property int inputRowSpacing: 10
        property int inputLabelFontSize: 16
        property bool inputLabelFontBold: true
        property color inputLabelColor: secondaryTextColor
        property int inputLabelWidth: 150
        property int inputFieldRightMargin: 50
        property int inputFieldHeight: 35
        property real inputFieldRadius: 4
        property color inputFieldBgReadOnly: dialogBackground
        property color inputFieldBgNormal: "#111827"
        property color inputFieldFocusBorderColor: "#60A5FA"
        property int inputFieldBorderWidth: 1
        property color inputFieldTextReadOnly: tertiaryTextColor
        property color inputFieldTextNormal: secondaryTextColor
        property int inputFieldFontSize: 15
        property int inputFieldPaddingLeft: 10
        property int inputFieldPaddingRightIcon: 45
        property int inputFieldPaddingRight: 10
        property int inputIconSize: 24
        property int inputIconRightMargin: 12
        property real inputIconFocusOpacity: 0.8
        property real inputIconNormalOpacity: 0.4
        property int startScreenIconColumnWidth: 100
        property int startScreenTopMargin: 60
        property int startScreenLayoutSpacing: 10
        property int startScreenOpenAreaHeight: 120
        property int startScreenOpenAreaBgMargin: -10
        property real startScreenOpenAreaRadius: 10
        property color startScreenOpenAreaHover: "#374151"
        property int startScreenOpenIconSize: 80
        property int startScreenOpenTextSize: 45
        property int startScreenOpenTextWeight: Font.DemiBold
        property int startScreenRecentIconSize: 60
        property real startScreenRecentIconOpacity: 0.5
        property int startScreenRecentTextSize: 32
        property int startScreenRecentTextWeight: Font.DemiBold
        property int startScreenHistoryItemHeight: 70
        property real startScreenHistoryItemRadius: 5
        property int startScreenHistoryItemSpacing: 15
        property int startScreenThumbSize: 50
        property real startScreenThumbRadius: 6
        property color startScreenThumbBgColor: "#374151"
        property int startScreenDeleteButtonSize: 35
        property real startScreenDeleteButtonRadius: 5
        property color startScreenDeleteButtonHoverColor: disabledTextColor
        property int scrollBarWidth: 8
        property real scrollBarRadius: 4
        property color metadataRightPanelBg: "#111827"
        property int metadataTopBarHeight: 50
        property int metadataLeftPanelWidth: 150
        property int metadataPanelMargin: 10
        property int metadataPanelSpacing: 12
        property int metadataActionBtnSize: 50
        property int metadataActionIconSize: 35
        property real metadataDisabledIconOpacity: 0.25
        property int metadataContentMargin: 20
        property int metadataScrollMargin: 15
        property int metadataContentSpacing: 8
        property int metadataSeparatorHeight: 1
        property color metadataSeparatorColor: "#374151"
        property int metadataRowWidthLarge: 450
        property int metadataRowWidthSmall: 300
        property real metadataReadOnlyOpacity: 0.8
        property int metadataDescriptionHeight: 80
        property int metadataDescriptionLabelTopMargin: 6
        property int metadataDescriptionPaddingTop: 6
        property int metadataDescriptionPaddingBottom: 6
        property int metadataDescriptionPaddingLeft: 8
        property int metadataDescriptionPaddingRight: 45
        property int metadataSaveBtnWidth: 150
        property int metadataSaveBtnHeight: 50
        property int metadataSaveBtnFontSize: 18
        property color metadataSaveBtnNormal: "#2563EB"
        property color metadataSaveBtnHover: "#3B82F6"
        property color metadataSaveBtnPressed: "#1D4ED8"
        property real metadataSaveBtnRadius: 6
        property int metadataBottomBarHeight1: 60
        property int metadataBottomBarHeight2: 50
        property color metadataBottomBarColor2: "#1F2937"
        property color cancelActionBtnNormal: "#DC2626"
        property color cancelActionBtnHover: "#EF4444"
        property color cancelActionBtnPressed: "#B91C1C"
        property int manipulationTopBarHeight: 50
        property int manipulationSidePanelWidth: 150
        property int manipulationPanelMargin: 10
        property int manipulationPanelSpacing: 12
        property int manipulationRotationSliderHeight: 475
        property int manipulationRotationSliderBgWidth: 40
        property int manipulationRotationSliderBgHeight: 270
        property int manipulationRotationSliderTrackWidth: 4
        property color manipulationRotationSliderTrackColor: canvasBorderColor
        property int manipulationRotationSliderTickWidthLarge: 25
        property int manipulationRotationSliderTickWidthSmall: 15
        property int manipulationRotationSliderTickHeightLarge: 5
        property int manipulationRotationSliderTickHeightSmall: 2
        property color manipulationRotationSliderTickColorActive: baseTextColor
        property color manipulationRotationSliderTickColorInactive: baseTextColor
        property int manipulationRotationSliderHandleSize: 24
        property real manipulationRotationSliderHandleRadius: 12
        property color manipulationRotationSliderHandleColor: colorWhite
        property color manipulationRotationSliderHandlePressedColor: "#E5E7EB"
        property color manipulationRotationSliderHandleBorderColor: tertiaryTextColor
        property int manipulationGridBtnSize: 50
        property int manipulationGridSpacing: 10
        property color manipulationConfirmBtnNormal: "#1D4ED8"
        property color manipulationConfirmBtnHover: "#2563EB"
        property color manipulationConfirmBtnPressed: "#1E40AF"
        property real manipulationConfirmBtnRadius: 4
        property color manipulationCropMaskColor: "#800000"
        property int manipulationCropHandleBaseSize: 26
        property color manipulationCropHandleColor: colorWhite
        property color manipulationCropHandleBorderColor: baseTextColor
        property color manipulationPanBtnActiveColor: baseInteractionPressed
        property color manipulationPanBtnHoverColor: baseInteractionHover
        property int manipulationZoomSliderWidth: 250
        property int manipulationZoomSliderBgWidth: 120
        property int manipulationZoomSliderBgHeight: 6
        property real manipulationZoomSliderBgRadius: 2
        property color manipulationZoomSliderBgColor: "#4B5563"
        property int manipulationZoomSliderHandleSize: 16
        property real manipulationZoomSliderHandleRadius: 8
        property color manipulationZoomSliderHandleColor: colorWhite
        property color manipulationZoomSliderHandleBorderColor: tertiaryTextColor
        property int manipulationBottomBarHeight1: 60
        property int manipulationBottomBarHeight2: 50
        property color manipulationBottomBarColor2: "#151C26"
        property int manipulationZoomBtnSpacing: 5
        property int filterStrengthSpacing: 20
        property int filterStrengthSeparatorHeight: 1
        property real filterStrengthSeparatorOpacity: 0.2
        property int filterStrengthTextSize: 18
        property int filterStrengthTextHeight: 45
        property int filterStrengthSliderHeight: 30
        property int filterStrengthSliderBgWidth: 130
        property int editorCornerListSpacing: 8
        property int editorCornerScrollBarWidth: 6
        property int editorCornerScrollBarRadius: 3
        property int editorToolBtnMinWidth: 130
        property int editorToolBtnHeight: 50
        property int editorToolBtnSpacing: 10
        property int editorToolBtnPadding: 15
        property int editorToolBtnIconSize: 28
        property int editorBottomBarSpacing: 15
        property int editorBottomBarMargin: 20
        property real editorInfoIconOpacity: 0.6
        property color editorOverlayBg: "#000000"
        property real editorPrintingOverlayOpacity: 0.6
        property real editorSaveOverlayOpacity: 0.7
        property int editorOverlayTextSizeLarge: 24
        property int editorOverlayTextSizeMedium: 22
        property color editorOverlayTextColor: colorWhite
        property int editorOverlayTextMargin: 40
        property int editorProgressBarHeight: 6
        property color editorProgressBarBgColor: "#4B5563"
        property real editorProgressBarRadius: 3
        property color editorProgressBarFillColor: "#EF4444"
        property real editorProgressBarFillRadius: 2
        property real editorPrintingAnimOpacityMin: 0.3
        property real editorPrintingBtnDisabledOpacity: 0.6
        property int drawingToolGridSpacing: 10
        property int drawingToolBtnSize: 60
        property int drawingToolIconSize: 50
        property int drawingDividerWidth: 130
        property int drawingSettingsSpacing: 10
        property int drawingSettingsWidth: 130
        property int drawingSettingsGroupSpacing: 15
        property int drawingSectionTitleSize: 22
        property int drawingSettingLabelSize: 15
        property int drawingColorSliderHeight: 20
        property color drawingRgbRedBg: "#7F1D1D"
        property color drawingRgbGreenBg: "#14532D"
        property color drawingRgbBlueBg: "#1E3A8A"
        property color drawingTextSelectionColor: "#1D4ED8"
    }

    property QtObject activeTheme: currentTheme === "light" ? themeLight : (currentTheme === "dark" ? themeDark : themeNormal)

    property color baseTextColor: activeTheme.baseTextColor
    property color secondaryTextColor: activeTheme.secondaryTextColor
    property color tertiaryTextColor: activeTheme.tertiaryTextColor
    property color disabledTextColor: activeTheme.disabledTextColor
    property color colorWhite: activeTheme.colorWhite
    property color baseInteractionHover: activeTheme.baseInteractionHover
    property color baseInteractionPressed: activeTheme.baseInteractionPressed
    property color dialogBackground: activeTheme.dialogBackground
    property color dialogHeaderBackground: activeTheme.dialogHeaderBackground
    property color overlayColor: activeTheme.overlayColor
    property color separatorColor: activeTheme.separatorColor
    property color canvasBorderColor: activeTheme.canvasBorderColor
    property real canvasBorderWidth: activeTheme.canvasBorderWidth
    property real canvasBorderLen: activeTheme.canvasBorderLen
    property real dialogRadius: activeTheme.dialogRadius
    property int fontTitleSize: activeTheme.fontTitleSize
    property int fontBodySize: activeTheme.fontBodySize
    property int fontWeight: activeTheme.fontWeight
    property color titleColor: activeTheme.titleColor
    property color messageColor: activeTheme.messageColor
    property real customButtonHeight: activeTheme.customButtonHeight
    property real buttonRadius: activeTheme.buttonRadius
    property color customButtonText: activeTheme.customButtonText
    property color customButtonNormal: activeTheme.customButtonNormal
    property color customButtonHover: activeTheme.customButtonHover
    property color customButtonPressed: activeTheme.customButtonPressed
    property real menuWidth: activeTheme.menuWidth
    property real menuRadius: activeTheme.menuRadius
    property color menuBackground: activeTheme.menuBackground
    property color menuBorder: activeTheme.menuBorder
    property int menuTextSize: activeTheme.menuTextSize
    property color menuText: activeTheme.menuText
    property real menuItemHeight: activeTheme.menuItemHeight
    property real menuItemRadius: activeTheme.menuItemRadius
    property real menuItemMargin: activeTheme.menuItemMargin
    property color menuItemHover: activeTheme.menuItemHover
    property color menuItemPressed: activeTheme.menuItemPressed
    property real menuSeparatorHeight: activeTheme.menuSeparatorHeight
    property color menuSeparatorColor: activeTheme.menuSeparatorColor
    property color btnCancelText: activeTheme.btnCancelText
    property color btnCancelNormal: activeTheme.btnCancelNormal
    property color btnCancelHover: activeTheme.btnCancelHover
    property color btnCancelPressed: activeTheme.btnCancelPressed
    property color btnCancelBorder: activeTheme.btnCancelBorder
    property color btnConfirmText: activeTheme.btnConfirmText
    property color btnConfirmNormal: activeTheme.btnConfirmNormal
    property color btnConfirmHover: activeTheme.btnConfirmHover
    property color btnConfirmPressed: activeTheme.btnConfirmPressed
    property int sliderTitleFontSize: activeTheme.sliderTitleFontSize
    property int sliderTitleFontWeight: activeTheme.sliderTitleFontWeight
    property color sliderTitleColor: activeTheme.sliderTitleColor
    property real sliderBgImplicitWidth: activeTheme.sliderBgImplicitWidth
    property real sliderBgImplicitHeight: activeTheme.sliderBgImplicitHeight
    property real sliderBgRadius: activeTheme.sliderBgRadius
    property color sliderBgColor: activeTheme.sliderBgColor
    property real sliderHandleImplicitWidth: activeTheme.sliderHandleImplicitWidth
    property real sliderHandleImplicitHeight: activeTheme.sliderHandleImplicitHeight
    property real sliderHandleRadius: activeTheme.sliderHandleRadius
    property color sliderHandleColor: activeTheme.sliderHandleColor
    property color sliderHandleBorderColor: activeTheme.sliderHandleBorderColor
    property real sliderHandleBorderWidth: activeTheme.sliderHandleBorderWidth
    property real sliderResetBtnWidth: activeTheme.sliderResetBtnWidth
    property real sliderResetBtnHeight: activeTheme.sliderResetBtnHeight
    property int sliderResetBtnFontSize: activeTheme.sliderResetBtnFontSize
    property color sliderResetBtnTextColor: activeTheme.sliderResetBtnTextColor
    property real sliderResetBtnBgHeight: activeTheme.sliderResetBtnBgHeight
    property color sliderResetBtnBgColor: activeTheme.sliderResetBtnBgColor
    property real sliderResetBtnBgRadius: activeTheme.sliderResetBtnBgRadius
    property int sliderValueFontSize: activeTheme.sliderValueFontSize
    property int sliderValueFontWeight: activeTheme.sliderValueFontWeight
    property color sliderValueColor: activeTheme.sliderValueColor
    property int iconButtonIconSize: activeTheme.iconButtonIconSize
    property int iconButtonColorFillPadding: activeTheme.iconButtonColorFillPadding
    property real iconButtonDisabledOpacity: activeTheme.iconButtonDisabledOpacity
    property real iconButtonNormalOpacity: activeTheme.iconButtonNormalOpacity
    property real iconButtonPressedScale: activeTheme.iconButtonPressedScale
    property int iconButtonAnimationDuration: activeTheme.iconButtonAnimationDuration
    property int iconButtonBgPadding: activeTheme.iconButtonBgPadding
    property color iconButtonSelectedColor: activeTheme.iconButtonSelectedColor
    property color iconButtonPressedColor: activeTheme.iconButtonPressedColor
    property color iconButtonHoveredColor: activeTheme.iconButtonHoveredColor
    property real iconButtonRadius: activeTheme.iconButtonRadius
    property int iconButtonTooltipDelay: activeTheme.iconButtonTooltipDelay
    property int filterButtonHeight: activeTheme.filterButtonHeight
    property int filterButtonSpacing: activeTheme.filterButtonSpacing
    property color filterButtonHoverColor: activeTheme.filterButtonHoverColor
    property int filterButtonBorderHeight: activeTheme.filterButtonBorderHeight
    property color filterButtonBorderColor: activeTheme.filterButtonBorderColor
    property int filterMenuWidth: activeTheme.filterMenuWidth
    property real filterMenuRadius: activeTheme.filterMenuRadius
    property color filterMenuBorderColor: activeTheme.filterMenuBorderColor
    property int filterMenuItemHeight: activeTheme.filterMenuItemHeight
    property int inputRowSpacing: activeTheme.inputRowSpacing
    property int inputLabelFontSize: activeTheme.inputLabelFontSize
    property bool inputLabelFontBold: activeTheme.inputLabelFontBold
    property color inputLabelColor: activeTheme.inputLabelColor
    property int inputLabelWidth: activeTheme.inputLabelWidth
    property int inputFieldRightMargin: activeTheme.inputFieldRightMargin
    property int inputFieldHeight: activeTheme.inputFieldHeight
    property real inputFieldRadius: activeTheme.inputFieldRadius
    property color inputFieldBgReadOnly: activeTheme.inputFieldBgReadOnly
    property color inputFieldBgNormal: activeTheme.inputFieldBgNormal
    property color inputFieldFocusBorderColor: activeTheme.inputFieldFocusBorderColor
    property int inputFieldBorderWidth: activeTheme.inputFieldBorderWidth
    property color inputFieldTextReadOnly: activeTheme.inputFieldTextReadOnly
    property color inputFieldTextNormal: activeTheme.inputFieldTextNormal
    property int inputFieldFontSize: activeTheme.inputFieldFontSize
    property int inputFieldPaddingLeft: activeTheme.inputFieldPaddingLeft
    property int inputFieldPaddingRightIcon: activeTheme.inputFieldPaddingRightIcon
    property int inputFieldPaddingRight: activeTheme.inputFieldPaddingRight
    property int inputIconSize: activeTheme.inputIconSize
    property int inputIconRightMargin: activeTheme.inputIconRightMargin
    property real inputIconFocusOpacity: activeTheme.inputIconFocusOpacity
    property real inputIconNormalOpacity: activeTheme.inputIconNormalOpacity
    property int startScreenIconColumnWidth: activeTheme.startScreenIconColumnWidth
    property int startScreenTopMargin: activeTheme.startScreenTopMargin
    property int startScreenLayoutSpacing: activeTheme.startScreenLayoutSpacing
    property int startScreenOpenAreaHeight: activeTheme.startScreenOpenAreaHeight
    property int startScreenOpenAreaBgMargin: activeTheme.startScreenOpenAreaBgMargin
    property real startScreenOpenAreaRadius: activeTheme.startScreenOpenAreaRadius
    property color startScreenOpenAreaHover: activeTheme.startScreenOpenAreaHover
    property int startScreenOpenIconSize: activeTheme.startScreenOpenIconSize
    property int startScreenOpenTextSize: activeTheme.startScreenOpenTextSize
    property int startScreenOpenTextWeight: activeTheme.startScreenOpenTextWeight
    property int startScreenRecentIconSize: activeTheme.startScreenRecentIconSize
    property real startScreenRecentIconOpacity: activeTheme.startScreenRecentIconOpacity
    property int startScreenRecentTextSize: activeTheme.startScreenRecentTextSize
    property int startScreenRecentTextWeight: activeTheme.startScreenRecentTextWeight
    property int startScreenHistoryItemHeight: activeTheme.startScreenHistoryItemHeight
    property real startScreenHistoryItemRadius: activeTheme.startScreenHistoryItemRadius
    property int startScreenHistoryItemSpacing: activeTheme.startScreenHistoryItemSpacing
    property int startScreenThumbSize: activeTheme.startScreenThumbSize
    property real startScreenThumbRadius: activeTheme.startScreenThumbRadius
    property color startScreenThumbBgColor: activeTheme.startScreenThumbBgColor
    property int startScreenDeleteButtonSize: activeTheme.startScreenDeleteButtonSize
    property real startScreenDeleteButtonRadius: activeTheme.startScreenDeleteButtonRadius
    property color startScreenDeleteButtonHoverColor: activeTheme.startScreenDeleteButtonHoverColor
    property int scrollBarWidth: activeTheme.scrollBarWidth
    property real scrollBarRadius: activeTheme.scrollBarRadius
    property color metadataRightPanelBg: activeTheme.metadataRightPanelBg
    property int metadataTopBarHeight: activeTheme.metadataTopBarHeight
    property int metadataLeftPanelWidth: activeTheme.metadataLeftPanelWidth
    property int metadataPanelMargin: activeTheme.metadataPanelMargin
    property int metadataPanelSpacing: activeTheme.metadataPanelSpacing
    property int metadataActionBtnSize: activeTheme.metadataActionBtnSize
    property int metadataActionIconSize: activeTheme.metadataActionIconSize
    property real metadataDisabledIconOpacity: activeTheme.metadataDisabledIconOpacity
    property int metadataContentMargin: activeTheme.metadataContentMargin
    property int metadataScrollMargin: activeTheme.metadataScrollMargin
    property int metadataContentSpacing: activeTheme.metadataContentSpacing
    property int metadataSeparatorHeight: activeTheme.metadataSeparatorHeight
    property color metadataSeparatorColor: activeTheme.metadataSeparatorColor
    property int metadataRowWidthLarge: activeTheme.metadataRowWidthLarge
    property int metadataRowWidthSmall: activeTheme.metadataRowWidthSmall
    property real metadataReadOnlyOpacity: activeTheme.metadataReadOnlyOpacity
    property int metadataDescriptionHeight: activeTheme.metadataDescriptionHeight
    property int metadataDescriptionLabelTopMargin: activeTheme.metadataDescriptionLabelTopMargin
    property int metadataDescriptionPaddingTop: activeTheme.metadataDescriptionPaddingTop
    property int metadataDescriptionPaddingBottom: activeTheme.metadataDescriptionPaddingBottom
    property int metadataDescriptionPaddingLeft: activeTheme.metadataDescriptionPaddingLeft
    property int metadataDescriptionPaddingRight: activeTheme.metadataDescriptionPaddingRight
    property int metadataSaveBtnWidth: activeTheme.metadataSaveBtnWidth
    property int metadataSaveBtnHeight: activeTheme.metadataSaveBtnHeight
    property int metadataSaveBtnFontSize: activeTheme.metadataSaveBtnFontSize
    property color metadataSaveBtnNormal: activeTheme.metadataSaveBtnNormal
    property color metadataSaveBtnHover: activeTheme.metadataSaveBtnHover
    property color metadataSaveBtnPressed: activeTheme.metadataSaveBtnPressed
    property real metadataSaveBtnRadius: activeTheme.metadataSaveBtnRadius
    property int metadataBottomBarHeight1: activeTheme.metadataBottomBarHeight1
    property int metadataBottomBarHeight2: activeTheme.metadataBottomBarHeight2
    property color metadataBottomBarColor2: activeTheme.metadataBottomBarColor2
    property color cancelActionBtnNormal: activeTheme.cancelActionBtnNormal
    property color cancelActionBtnHover: activeTheme.cancelActionBtnHover
    property color cancelActionBtnPressed: activeTheme.cancelActionBtnPressed
    property int manipulationTopBarHeight: activeTheme.manipulationTopBarHeight
    property int manipulationSidePanelWidth: activeTheme.manipulationSidePanelWidth
    property int manipulationPanelMargin: activeTheme.manipulationPanelMargin
    property int manipulationPanelSpacing: activeTheme.manipulationPanelSpacing
    property int manipulationRotationSliderHeight: activeTheme.manipulationRotationSliderHeight
    property int manipulationRotationSliderBgWidth: activeTheme.manipulationRotationSliderBgWidth
    property int manipulationRotationSliderBgHeight: activeTheme.manipulationRotationSliderBgHeight
    property int manipulationRotationSliderTrackWidth: activeTheme.manipulationRotationSliderTrackWidth
    property color manipulationRotationSliderTrackColor: activeTheme.manipulationRotationSliderTrackColor
    property int manipulationRotationSliderTickWidthLarge: activeTheme.manipulationRotationSliderTickWidthLarge
    property int manipulationRotationSliderTickWidthSmall: activeTheme.manipulationRotationSliderTickWidthSmall
    property int manipulationRotationSliderTickHeightLarge: activeTheme.manipulationRotationSliderTickHeightLarge
    property int manipulationRotationSliderTickHeightSmall: activeTheme.manipulationRotationSliderTickHeightSmall
    property color manipulationRotationSliderTickColorActive: activeTheme.manipulationRotationSliderTickColorActive
    property color manipulationRotationSliderTickColorInactive: activeTheme.manipulationRotationSliderTickColorInactive
    property int manipulationRotationSliderHandleSize: activeTheme.manipulationRotationSliderHandleSize
    property real manipulationRotationSliderHandleRadius: activeTheme.manipulationRotationSliderHandleRadius
    property color manipulationRotationSliderHandleColor: activeTheme.manipulationRotationSliderHandleColor
    property color manipulationRotationSliderHandlePressedColor: activeTheme.manipulationRotationSliderHandlePressedColor
    property color manipulationRotationSliderHandleBorderColor: activeTheme.manipulationRotationSliderHandleBorderColor
    property int manipulationGridBtnSize: activeTheme.manipulationGridBtnSize
    property int manipulationGridSpacing: activeTheme.manipulationGridSpacing
    property color manipulationConfirmBtnNormal: activeTheme.manipulationConfirmBtnNormal
    property color manipulationConfirmBtnHover: activeTheme.manipulationConfirmBtnHover
    property color manipulationConfirmBtnPressed: activeTheme.manipulationConfirmBtnPressed
    property real manipulationConfirmBtnRadius: activeTheme.manipulationConfirmBtnRadius
    property color manipulationCropMaskColor: activeTheme.manipulationCropMaskColor
    property int manipulationCropHandleBaseSize: activeTheme.manipulationCropHandleBaseSize
    property color manipulationCropHandleColor: activeTheme.manipulationCropHandleColor
    property color manipulationCropHandleBorderColor: activeTheme.manipulationCropHandleBorderColor
    property color manipulationPanBtnActiveColor: activeTheme.manipulationPanBtnActiveColor
    property color manipulationPanBtnHoverColor: activeTheme.manipulationPanBtnHoverColor
    property int manipulationZoomSliderWidth: activeTheme.manipulationZoomSliderWidth
    property int manipulationZoomSliderBgWidth: activeTheme.manipulationZoomSliderBgWidth
    property int manipulationZoomSliderBgHeight: activeTheme.manipulationZoomSliderBgHeight
    property real manipulationZoomSliderBgRadius: activeTheme.manipulationZoomSliderBgRadius
    property color manipulationZoomSliderBgColor: activeTheme.manipulationZoomSliderBgColor
    property int manipulationZoomSliderHandleSize: activeTheme.manipulationZoomSliderHandleSize
    property real manipulationZoomSliderHandleRadius: activeTheme.manipulationZoomSliderHandleRadius
    property color manipulationZoomSliderHandleColor: activeTheme.manipulationZoomSliderHandleColor
    property color manipulationZoomSliderHandleBorderColor: activeTheme.manipulationZoomSliderHandleBorderColor
    property int manipulationBottomBarHeight1: activeTheme.manipulationBottomBarHeight1
    property int manipulationBottomBarHeight2: activeTheme.manipulationBottomBarHeight2
    property color manipulationBottomBarColor2: activeTheme.manipulationBottomBarColor2
    property int manipulationZoomBtnSpacing: activeTheme.manipulationZoomBtnSpacing
    property int filterStrengthSpacing: activeTheme.filterStrengthSpacing
    property int filterStrengthSeparatorHeight: activeTheme.filterStrengthSeparatorHeight
    property real filterStrengthSeparatorOpacity: activeTheme.filterStrengthSeparatorOpacity
    property int filterStrengthTextSize: activeTheme.filterStrengthTextSize
    property int filterStrengthTextHeight: activeTheme.filterStrengthTextHeight
    property int filterStrengthSliderHeight: activeTheme.filterStrengthSliderHeight
    property int filterStrengthSliderBgWidth: activeTheme.filterStrengthSliderBgWidth
    property int editorCornerListSpacing: activeTheme.editorCornerListSpacing
    property int editorCornerScrollBarWidth: activeTheme.editorCornerScrollBarWidth
    property int editorCornerScrollBarRadius: activeTheme.editorCornerScrollBarRadius
    property int editorToolBtnMinWidth: activeTheme.editorToolBtnMinWidth
    property int editorToolBtnHeight: activeTheme.editorToolBtnHeight
    property int editorToolBtnSpacing: activeTheme.editorToolBtnSpacing
    property int editorToolBtnPadding: activeTheme.editorToolBtnPadding
    property int editorToolBtnIconSize: activeTheme.editorToolBtnIconSize
    property int editorBottomBarSpacing: activeTheme.editorBottomBarSpacing
    property int editorBottomBarMargin: activeTheme.editorBottomBarMargin
    property real editorInfoIconOpacity: activeTheme.editorInfoIconOpacity
    property color editorOverlayBg: activeTheme.editorOverlayBg
    property real editorPrintingOverlayOpacity: activeTheme.editorPrintingOverlayOpacity
    property real editorSaveOverlayOpacity: activeTheme.editorSaveOverlayOpacity
    property int editorOverlayTextSizeLarge: activeTheme.editorOverlayTextSizeLarge
    property int editorOverlayTextSizeMedium: activeTheme.editorOverlayTextSizeMedium
    property color editorOverlayTextColor: activeTheme.editorOverlayTextColor
    property int editorOverlayTextMargin: activeTheme.editorOverlayTextMargin
    property int editorProgressBarHeight: activeTheme.editorProgressBarHeight
    property color editorProgressBarBgColor: activeTheme.editorProgressBarBgColor
    property real editorProgressBarRadius: activeTheme.editorProgressBarRadius
    property color editorProgressBarFillColor: activeTheme.editorProgressBarFillColor
    property real editorProgressBarFillRadius: activeTheme.editorProgressBarFillRadius
    property real editorPrintingAnimOpacityMin: activeTheme.editorPrintingAnimOpacityMin
    property real editorPrintingBtnDisabledOpacity: activeTheme.editorPrintingBtnDisabledOpacity
    property int drawingToolGridSpacing: activeTheme.drawingToolGridSpacing
    property int drawingToolBtnSize: activeTheme.drawingToolBtnSize
    property int drawingToolIconSize: activeTheme.drawingToolIconSize
    property int drawingDividerWidth: activeTheme.drawingDividerWidth
    property int drawingSettingsSpacing: activeTheme.drawingSettingsSpacing
    property int drawingSettingsWidth: activeTheme.drawingSettingsWidth
    property int drawingSettingsGroupSpacing: activeTheme.drawingSettingsGroupSpacing
    property int drawingSectionTitleSize: activeTheme.drawingSectionTitleSize
    property int drawingSettingLabelSize: activeTheme.drawingSettingLabelSize
    property int drawingColorSliderHeight: activeTheme.drawingColorSliderHeight
    property color drawingRgbRedBg: activeTheme.drawingRgbRedBg
    property color drawingRgbGreenBg: activeTheme.drawingRgbGreenBg
    property color drawingRgbBlueBg: activeTheme.drawingRgbBlueBg
    property color drawingTextSelectionColor: activeTheme.drawingTextSelectionColor
}